### ISSUE TITLE
DX-5107: Create a new branch for ACMS V2 testing

### ISSUE THREAD

**Issue by nagwani** [acquia/drupal-recommended-project#113]
Please create a branch on acquia/drupal-recommended-project` that removes `acquia/acquia_cms` and adds `Acquia/acquia-cms-starterkit`

We want to test ACMS V2 versions via the drupal-recommended-project.

Please note this is under development and not meant to be used by anyone else outside of Acquia, so I am not sure if there are any specific perms to be managed.

Thank you!

**Comment by balsama** [comment]
Created branch here: https://github.com/acquia/drupal-recommended-project/tree/113-acms-v2

**Comment by danepowell** [comment]
This is a public repo, if you want to keep this work private you should clone it to a private fork.

**Comment by nagwani** [comment]
Thank you! 
Since acquia-cms-starterkit is a private repo, we should be good!
