### ISSUE TITLE
DX-5123: Update composer to use stability version for acquia/acquia-cms-starterkit

### ISSUE THREAD

**Issue by vishalkhode1** [acquia/drupal-recommended-project#142]
We need to update [composer](https://github.com/acquia/drupal-recommended-project/blob/113-acms-v2/composer.json#L14) dependency to use stability version constraint for [acquia/acquia_cms-starterkit](https://github.com/acquia/acquia-cms-starterkit) repo in branch [113-acms-v2](https://github.com/acquia/drupal-recommended-project/tree/113-acms-v2).

Proposed changes:
```
diff --git a/composer.json b/composer.json
index f93f5d4..9a2177d 100644
--- a/composer.json
+++ b/composer.json
@@ -11,7 +11,7 @@
     ],
     "require": {
         "php": ">=7.4",
-        "acquia/acquia-cms-starterkit": "*",
+        "acquia/acquia-cms-starterkit": "^1.0",
```

**Comment by balsama** [comment]
Hi. Is there anything preventing you from forking the repo and performing whatever tests you need there? Or use a local I'm not sure we need to maintain a separate branch on the actual repo for whatever you're doing. Or just use a local [path-based](https://getcomposer.org/doc/05-repositories.md#path) repository for your testing.

**Comment by nagwani** [comment]
We will need to provide additional folks outside of our team to do the testing as well. We were hoping to follow the same process as we do today on the main branch and hence the need for the separate branch. Once we release, this branch can be deleted. 

Does that help?
