### ISSUE TITLE
[Feature request] Add reference to Drupal 9 Spec Tool

### ISSUE THREAD

**Issue by bemarlan** [acquia/drupal-recommended-project#18]
It is Acquia best practice for Drupal builds to use the [Drupal Spec tool](https://github.com/acquia/drupal-spec-tool). For Drupal 9 specifically, [^4.0.0](https://github.com/acquia/drupal-spec-tool/releases/tag/4.0.0) should be used.

Since the drupal-recommended-project does not support behat out-of-the-box, it does not make sense to include the Drupal Spec Tool package in composer.json. (The package is dependent on behat, and in general just hooks the Drupal Spec Sheet spreadsheet into behat.) However, it does make sense to reference the [Drupal Spec Tool spreadsheet](https://github.com/acquia/drupal-spec-tool/tree/4.0.0#google-sheet) in this project.

**Comment by danepowell** [comment]
I agree that people should use the spec tool if they use Behat, but I'm not sure where this naturally fits within the project template. I think this sort of recommendation belongs in documentation, rather than a project template.

Where would you naturally look for such a reference?
