### ISSUE TITLE
Provide "custom" package directories

### ISSUE THREAD

**Issue by danepowell** [acquia/drupal-recommended-project#3]
composer.json specifies that custom packages go in custom directories (i.e. docroot/modules/custom) but those directories don't actually get created until someone adds such a package.

To provide a clearer indication to users about where they should put their first custom package, I think we should provide those (empty) directories out of the box.

This will also prevent blt validate failures.

**Comment by ba66e77** [comment]
I assume you'd drop a README in those so that its clear what the `modules\custom` dir is for and so that it can be committed to git?

**Comment by danepowell** [comment]
Yeah or use .gitkeep. Could copy from https://github.com/acquia/blt-project/tree/11.x/docroot/modules/custom
