### ISSUE TITLE
ACMS-1838: Need to enable PHP 8.2 testing

### ISSUE THREAD

**Issue by secretsayan** [acquia/drupal-recommended-project#391]
I have created the following PRs -
- https://github.com/acquia/drupal-recommended-project/pull/389 for 1.x branch. 
- https://github.com/acquia/drupal-recommended-project/pull/390 for  master branch.

Please review and merge them. Let me know if you have queries.

**Comment by vishalkhode1** [comment]
@secretsayan Both PR's are merged. Hence, closing this.
