### ISSUE TITLE
ACMS-1941: Fatal errors thrown by SubtypeBreadcrumb

### ISSUE THREAD

**Issue by mandclu-acquia** [acquia/drupal-recommended-project#444]
**Describe the bug**
I was getting a fatal error while trying to view an event node that had been created as part of the demo content:

Error: Call to a member function getPath() on null in Drupal\acquia_cms_common\SubtypeBreadcrumb->getListPageLink() (line 180 of /var/www/html/docroot/modules/contrib/acquia_cms_common/src/SubtypeBreadcrumb.php).

The SubtypeBreadcrumb throws multiple fatal errors. The error above happens because the getListPageLink tests internally if the facet source is an instance of SearchApiFacetSourceInterface but can't return a properly constructed link if not. For this, I would propose wrapping the the call to this method in the build method, in a check that the facet source is the expected instance type.

With that fixed, I now get a new error:

Error: Call to a member function getPath() on null in Drupal\facets_pretty_paths\Plugin\facets\url_processor\FacetsPrettyPathsUrlProcessor->buildUrls() (line 165 of /var/www/html/docroot/modules/contrib/facets_pretty_paths/src/Plugin/facets/url_processor/FacetsPrettyPathsUrlProcessor.php).

I had installed demo content and then replaced the standard ACMS Event views with those from the Smart Date Starter Kit and Smart Date Calendar Kit, which I suspect is related to the errors. That said, the code should be able to handle unexpected output without fatal errors.

**Comment by vipin-mittal-acquia** [comment]
Hello @mandclu-acquia,

We followed below steps to reproduce issue:

1. Installed ACMS community starter kit with demo content.
2. Enabled smart date module, configured and run migrate command .
3. Enabled the smart_date_recur & add_content_by_bundle modules.
4. Successfully imported events from the smart date calendar kit Yaml file. Refer Yaml file link https://git.drupalcode.org/project/smart_date_calendar_kit/-/blob/2.0.x/config/install/views.view.events_calendar.yml

Please refer to the screenshot attached today with the steps followed. There are no errors logged in Watchdog.

Could you please let me know if I missed any steps?

**Comment by vishalkhode1** [comment]
Closing as Outdated.
