### ISSUE TITLE
Do not prompt when installing plugins with Composer 2.2.x

### ISSUE THREAD

**Issue by anavarre** [acquia/drupal-recommended-project#65]
With Composer 2.2.x we have more secure plugin execution. As such, Composer is going to ask user input before pulling plugins. For Acquia's Drupal recommended project, the user is prompted 5-6 times, which is annoying and confusing.

See https://blog.packagist.com/composer-2-2/#more-secure-plugin-execution

**Comment by danepowell** [comment]
@grasmash does this have anything to do with the "allow-plugins" config you added in https://github.com/acquia/drupal-recommended-project/commit/769b1a62b1bf5b829142a122a361e0e28598e108

**Comment by grasmash** [comment]
Yes. That should be resolved now.
