### ISSUE TITLE
Is Archived package acquia/memcache-settings still recommended?

### ISSUE THREAD

**Issue by naveenvalecha** [acquia/drupal-recommended-project#690]
The repo https://github.com/acquia/memcache-settings is archived and recommended when creating a new project. Is that package still recommended to use on a project having Acquia Cloud Next subscription?

**Comment by vishalkhode1** [comment]
Hi @naveenvalecha 
Yes, if you are Acquia Cloud Next, then it's not recommended.

**Comment by vishalkhode1** [comment]
The [README](https://github.com/acquia/drupal-recommended-project) is updated to reflect the same. Hence, closing this.
