### ISSUE TITLE
Remove drupal/mysql Package

### ISSUE THREAD

**Issue by mikemadison13** [acquia/drupal-recommended-project#87]
The drupal/mysql56 package is no longer required for Drupal 9. This should be removed from https://github.com/acquia/drupal-recommended-project/blob/master/composer.json#L22

**Comment by danepowell** [comment]
> The drupal/mysql56 package is no longer required for Drupal 9

Specifically, I would say it's no longer required on Acquia hosting since [Acquia EOL'd MySQL 5.6 a year ago](https://docs.acquia.com/support/eol/#end-of-life-process-completion-list). Let me know if that's not right.
